Feature/create book entity
Cayman4010/online-book-store pull request #1
Opened 2023-10-16 14:30 UTC by Cayman4010

2023-10-16 20:15 UTC, viacheslav-torbin approved these changes

2023-10-16 20:15 UTC, viacheslav-torbin commented on query
Why do we need this file?)

2023-10-16 20:31 UTC, Cayman4010 commented on query
I don`t know what is it :) It was created by default

2023-10-17 09:50 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2023-10-17 09:50 UTC, liliia-ponomarenko commented on pom.xml
> +        </dependency>
Do you really need all these dependencies?

2023-10-17 09:50 UTC, liliia-ponomarenko commented on query
so, let’s  remove it ;)

2023-10-17 09:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/exception/DataProcessingException.java
> +    }
Do you use this constructor? Maybe you should add some realization;)

2023-10-17 09:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/model/Book.java
> +@Data
Lombok is a great library but be [attentive when using it with Entity](https://jpa-buddy.com/blog/lombok-and-jpa-what-may-go-wrong/)

2023-10-17 09:50 UTC, liliia-ponomarenko commented on src/main/java/bookstore/repository/impl/BookRepositoryImpl.java
> +            return getAllBooks.getResultList();
it can be an inline variable;)

2023-10-17 12:50 UTC, liliia-ponomarenko approved these changes
Great 😊

2023-10-17 15:53 UTC, merged